
name = "ncrr"
main = "worker/index.ts"
compatibility_date = "2024-01-01"

# Static Assets (Frontend)
[assets]
directory = "dist"
binding = "ASSETS"

# R2 Bucket for Images
[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "ncr"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "ncr-drive-db"
database_id = "a21d9f85-92cd-4b94-ad40-0617c9e6b24f"

[vars]
ENVIRONMENT = "production"
OWNER_EMAIL = "ncrdrivecar@gmail.com"
OWNER_PASSWORD = "change_me_in_dashboard"
# Default hash placeholder (Specific password logic handled in worker)
OWNER_PASSWORD_HASH = "$2a$10$w.2.1.2.3.4.5.6.7.8.9.0.1.2.3.4.5.6.7.8.9.0.1" 
GOOGLE_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbzPZyzeLWmdPQpbVzpg6qYjWQ61iVj_8v-qS6zmjrhY17apui_235uwKzx_w37pP1QJbQ/exec"
TELEGRAM_BOT_TOKEN = "8402658132:AAH7lQcAyF9x3fqa7yAyQqYrP2_PTARa3ts"
TELEGRAM_OWNER_CHAT_ID = "8258614791"
